---
title: "R Notebook"
output: html_notebook
---

Import Data

```{r}
training_set <- as.matrix(read.csv("./data/training_set.csv", row.names = 1))
test_set <- as.matrix(read.csv("./data/test_set.csv", row.names = 1))
```

```{r}
rownames(recommendations) <- rownames(test_set)
submission <- reshape2::melt(recommendations)
head(submission)
```

```{r}
sub_training_set <- training_set[, 1:10]
sub_test_set <- test_set[, 1:8]


get_eculidean_distance <- function(x, y) {
  return(sqrt(sum((x-y)^2)))
}

get_recommendations <- function(train, test_col) {
  euclidean_distances <- apply(train, 2, function(x) get_eculidean_distance(x, test_col))
  
  neighbor <- train[, which.min(euclidean_distances)]
  
  neighbor[which(test_col!=0)] <- 0
  
  res <- rep(0, length(test_col))
  res[order(neighbor, decreasing = TRUE)[1:5]] <- 1
  
  
  return(res)
}

recommendations <- pbapply::pbapply(test_set, 2, function(x) get_recommendations(training_set, x))
```

```{r}
table(colSums(recommendations != 0))
```

```{r}
rownames(recommendations) <- rownames(test_set)
submission <- reshape2::melt(recommendations)
head(submission)
```

```{r}
sample_submission <- read.csv("data/sample_submission.csv", row.names = 1)
submission_ids <- read.csv("data/submission_ids.csv", row.names = 1)
head(sample_submission)
```

```{r}
sample_submission$Expected <- submission$value
write.csv(sample_submission, "my_submission.csv", row.names = FALSE)
```









```{r}
# calculate distance between vector x of length n and all columns in A of dimensions m x n
RecommendByAbsoluteNN <- function(A, x) {
  print("-------------")
  # calculate absolute distance between vector x and each column in A
  distances <- apply(A, 2, function(y) sum(abs(y - x)))
  print(distances)
  
  # select the nearest neighbor based on absolute difference
  training_nn <- A[, which.min(distances)]

  # don't recommend any values which are non-zero in the test sample
  training_nn[which(x != 0)] <- 0
  
  # generate 5 recommendations
  recommendations <- rep(0, length(x))
  print(recommendations)
  print(unname(training_nn))
  print(order(training_nn, decreasing = TRUE)[1:5])
  recommendations[order(training_nn, decreasing = TRUE)[1:5]] <- 1

  return(recommendations)
}


apply(sub_test_set, 2, function(x) RecommendByAbsoluteNN(sub_training_set, x))
```

```{r}
# loop 1
x <- sub_test_set[, 1]
training_nn <- sub_training_set[, 6]
training_nn[which(x != 0)]
```

```{r}
order(c(1, 1, 3, 2, 1, 1, 2, 3, 4, 3), decreasing = TRUE)
```
```{r}
t<-rep(0, 5)
```

